services:
  coff-api:
    image: ${DOCKER_REGISTRY-}coffapi
    container_name: coff.api
    build:
      context: .
      dockerfile: src/coff.API/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  coff-database:
    image: postgres:latest
    container_name: coff.database
    environment:
      - POSTGRES_DB=coff
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  coff-seq:
    image: datalust/seq:2024.3
    container_name: coff.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
        
  coff-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: coff.blob-storage
    volumes:
      - ./.containers/blob_storage/data:/data
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"
  
